dev:
  push:
    - name: writerside-build
      stages:
        - name: generate-docs
          jobs:
            - name: build-pdf
              image: jetbrains/writerside-builder:2025.04.8412
              env:
                SOURCE_DIR: /opt/sources
                MODULE_INSTANCE: Writerside/mgcd
                OUTPUT_DIR: /opt/sources/output
                RUNNER: other
                PDF: PDF.xml
              commands:
                - echo "Building PDF with Writerside..."
              workspace: /opt/sources
