dev:
  push:
    - name: writerside-build
      stages:
        - name: generate-docs
          jobs:
            - name: build-html
              image: jetbrains/writerside-builder:2025.04.8412
              env:
                SOURCE_DIR: /workspace
                OUTPUT_DIR: /workspace/output
                MODULE_INSTANCE: Writerside/mgcd
                RUNNER: other
              commands:
                - mkdir -p "${OUTPUT_DIR}"
                - echo "构建日志：${OUTPUT_DIR}"
              artifacts:
                paths:
                  - "${OUTPUT_DIR}/**"
