dev:
  push:
    - name: build-writeside
      docker:
        image: jetbrains/writerside-builder:2025.04.8412
      volumes:
        - ./output:copy-on-write
      stages:
        - name: build
          script: |
            # 直接执行构建命令（无需docker run）
            writerside generate --source=/workspace --output=/workspace/output
            ls -la /workspace/output/
