dev:
  push:
    - name: writerside-build
      stages:
        - name: generate-docs
          jobs:
            - name: build-html
              image: jetbrains/writerside-builder:2025.04.8412
              env:
                SOURCE_DIR: /opt/sources
                MODULE_INSTANCE: Writerside/mgcd
                OUTPUT_DIR: /opt/sources/output
                RUNNER: other
              commands:
                - mkdir -p "${OUTPUT_DIR}"
                - echo "构建日志：${OUTPUT_DIR}"
              workspace: /opt/sources
              artifacts:
                paths:
                  - "${OUTPUT_DIR}/**"
