dev:
  push:
    - name: writerside-build
      docker:
        image: jetbrains/writerside-builder:2025.04.8412
      volumes:
        - ./output:copy-on-write
      stages:
        - name: build-docs
          script: |
            docker run --rm -v $(pwd):/opt/sources \
              -e SOURCE_DIR=/opt/sources \
              -e MODULE_INSTANCE=Writerside/hi \
              -e OUTPUT_DIR=/opt/sources/output \
              jetbrains/writerside-builder:2025.04.8412
            ls -la ./output/
