dev:
  push:
    - name: pipeline-1
      stages:
        - name: stage-1
          jobs:
            - name: job-1
              image: jetbrains/writerside-builder:2025.04.8412
              args:
                - "-v .:/opt/sources"
                - "-e SOURCE_DIR=/opt/sources"
                - "-e MODULE_INSTANCE=Writerside/hi"
                - "-e OUTPUT_DIR=/opt/sources/output"
                - "-e RUNNER=other"
                - "-e PDF=PDF.xml"
