dev:
  push:
    - name: build-writeside
      docker:
        image: jetbrains/writerside-builder:2025.04.8412
      volumes:
        - ./output:copy-on-write
      stages:
        - name: build
          script: |
            /opt/writerside/bin/build.sh --input=/workspace --output=/workspace/output || {
              echo "Fallback: Using alternative command...";
              writerside-cli generate --source=/workspace --output=/workspace/output;
            }
            ls -la /workspace/output/
