dev:
  push:
    - name: pipeline-1
      stages:
        - name: stage-1
          jobs:
            - name: job-1
              env:
                SOURCE_DIR: ./
                MODULE_INSTANCE: Writerside/mgcd
                OUTPUT_DIR: ./output
                RUNNER: other
                PDF: PDF.xml
              volumes:
                - ./:./
              image: jetbrains/writerside-builder:2025.04.8412
