dev:
  push:
    - name: writerside-build
      stages:
        - name: generate-docs
          jobs:
            - name: build-html
              image: jetbrains/writerside-builder:2025.04.8412
              env:
                SOURCE_DIR: /workspace
                OUTPUT_DIR: /workspace/output
                MODULE_INSTANCE: Writerside/mgcd
                RUNNER: other
              commands:
                - mkdir -p "${OUTPUT_DIR}"
                - echo "===== 启动构建器 ====="
                - export DISPLAY=:99 && Xvfb :99 &
                - /opt/builder/bin/idea.sh helpbuilderinspect \
                    --source-dir "${SOURCE_DIR}" \
                    --product "${MODULE_INSTANCE}" \
                    --runner "${RUNNER}" \
                    --output-dir "${OUTPUT_DIR}"
              artifacts:
                paths:
                  - "${OUTPUT_DIR}/**"
