dev:
  push:
    - name: writerside-build
      stages:
        - name: generate-docs
          jobs:
            - name: build-html
              image: jetbrains/writerside-builder:2025.04.8412
              env:
                SOURCE_DIR: /opt/sources
                MODULE_INSTANCE: Writerside/mgcd
                OUTPUT_DIR: /opt/sources/output
                RUNNER: other
              commands:
                - echo "Building HTML documentation..."
                - echo "===== 生成目录结构 ====="
                - ls -laR "${OUTPUT_DIR}"
              workspace: /opt/sources
              artifacts:
                paths:
                  - "${OUTPUT_DIR}/**"
