name: Build documentation

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: "Writerside/mgcd"
  ARTIFACT: "webHelpMGCD2-all.zip"
  DOCKER_VERSION: "242.21870"
  ALGOLIA_ARTIFACT: "algolia-indexes-MGCD.zip"
  ALGOLIA_APP_NAME: "AMQJCXFVUL"
  ALGOLIA_INDEX_NAME: "mgcd-hypercol"
  ALGOLIA_KEY: "${{ secrets.ALGOLIA_KEY }}"
  CONFIG_JSON_PRODUCT: "mgcd"
  CONFIG_JSON_VERSION: "2.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docs
  #         path: artifacts

  #     - name: Test documentation
  #       uses: JetBrains/writerside-checker-action@v1
  #       with:
  #         instance: ${{ env.INSTANCE }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: Set target branch
        id: set_branch
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TARGET_BRANCH=main-pages" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "TARGET_BRANCH=dev-pages" >> $GITHUB_ENV
          else
            echo "Unsupported branch, skipping deployment."
            exit 1
          fi

      - name: Push pages to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REPO_AND_PACKAGES }}
          publish_dir: ./dir
          publish_branch: ${{ env.TARGET_BRANCH }}
          destination_dir: ./docs

  # publish-indexes:
  #   needs: [build, deploy]
  #   runs-on: ubuntu-latest
  #   container:
  #     image: registry.jetbrains.team/p/writerside/builder/algolia-publisher:2.0.32-3
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docs
  #     - name: Unzip artifact
  #       run: |
  #         unzip -O UTF-8 -qq '${{ env.ALGOLIA_ARTIFACT }}' -d algolia-indexes
  #         env algolia-key='${{env.ALGOLIA_KEY}}' java -jar /opt/builder/help-publication-agent.jar \
  #         update-index \
  #         --application-name '${{env.ALGOLIA_APP_NAME}}' \
  #         --index-name '${{env.ALGOLIA_INDEX_NAME}}' \
  #         --product '${{env.CONFIG_JSON_PRODUCT}}' \
  #         --version '${{env.CONFIG_JSON_VERSION}}' \
  #         --index-directory algolia-indexes/ \
  #         2>&1 | tee algolia-update-index-log.txt
