name: Build Dev Documentation

on:
  pull_request:
    branches: 
      - main
    types: [opened, synchronize]

permissions:
  id-token: write
  pages: write

env:
  INSTANCE: "Writerside/mgcd"
  ARTIFACT: "webHelpMGCD2-all.zip"
  DOCKER_VERSION: "2025.04.8412"
  ALGOLIA_ARTIFACT: "algolia-indexes-MGCD.zip"
  ALGOLIA_APP_NAME: "PYZCIVPXES"
  ALGOLIA_INDEX_NAME: "mgc_docs_crawler_pages"
  ALGOLIA_KEY: "${{ secrets.ALGOLIA_KEY }}"
  CONFIG_JSON_PRODUCT: "mgcd"
  CONFIG_JSON_VERSION: "2.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Build docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
            artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Unzip artifact
        run: unzip -O UTF-8 -qq '${{ env.ARTIFACT }}' -d dir

      - name: Push pages to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REPO_AND_PACKAGES }}
          publish_dir: ./dir
          publish_branch: dev-pages
          destination_dir: ./docs
