name: Push to CNB.cool

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add CNB.cool repository as remote
        run: |
          git remote add target https://$GITHUB_ACTOR:${{ secrets.CNB_TOKEN }}@cnb.cool/${{ secrets.CNB_USERNAME }}/mgc-docs.git
          git fetch target
          
      - name: Push changes to CNB.cool repository
        run: |
          git push --force --set-upstream target dev  # 推送到dev分支
        env:
          GITHUB_TOKEN: ${{ secrets.CNB_TOKEN }}  # 如果还需要其他GitHub secrets，留此处
