name: Push to CNB.cool

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git push https://${{ secrets.USERNAME }}:${{ secrets.TOKEN }}@cnb.cool/HyperCol/mgc-docs.git main
